version: '{build}'

install:
  - nuget install -OutputDirectory Stuff/ -ExcludeVersion
  - ps: Invoke-WebRequest https://files.fusetools.com/tooling/iyVp8kwQ0vLn-mesa-17.2.3.500.zip -OutFile mesa.zip
  - ps: Expand-Archive mesa.zip mesa

build_script:
  - Stuff\uno --trace doctor

before_test:
  - ps: |
      Get-ChildItem -Path Source -Recurse -Include *Test.unoproj | Select-Object -ExpandProperty DirectoryName | Foreach-Object {
        $buildDir = Join-Path $_ build\Test\DotNet
        New-Item -Force -ItemType directory -Path $buildDir | Out-Null
        Copy-Item -Path mesa\x64\opengl32.dll -Destination (Join-Path $buildDir opengl32.dll)
      }

test_script:
  - Stuff\uno --trace test -tDotNet Source
