language: cpp
os: osx

install:
  - brew update
  - brew install mono
  - brew install ccache
  - Stuff/stuff install Stuff

script:
  - Stuff/uno doctor
  - Stuff/uno test -tnative --timeout=30 Source
