language: cpp
os: osx
osx_image: xcode8.3

install:
  - brew update
  - brew install mono
  - brew install ccache
  - Stuff/stuff install Stuff

before_script:
  - export VERBOSE=1
  - export MACOSX_DEPLOYMENT_TARGET=10.9

script:
  - Stuff/uno doctor
  - Stuff/uno test -v -v -tnative --timeout=30 Source
